ALTER TABLE generated_tests
    ADD COLUMN IF NOT EXISTS correct_marks DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS wrong_marks DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS unattempted_marks DOUBLE PRECISION;